### ISSUE TITLE
Crash when playing songs

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#22]
It's works for few hours and crash.
```bash
# deefuzzer config.yaml 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/DeeFuzzer-0.6.6-py2.7.egg/deefuzzer/station.py", line 657, in run
    self.set_read_mode()
  File "/usr/local/lib/python2.7/dist-packages/DeeFuzzer-0.6.6-py2.7.egg/deefuzzer/station.py", line 573, in set_read_mode
    self.song = song.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
```

In my log:
```bash
2014-08-07 23:09:09,882 INFO DeeFuzzing on station_name :  id = 149, name = mysong.mp3
2014-08-07 23:30:06,485 INFO Starting DeeFuzzer
```

@yomguy The track_id 150 crash deefuzzer. It contain a "è" character. I don't know why, It can read other tracks with "é" or "ê" or "é" and "è" in same word but not this one. Do you have any idea? Do you have a tool to check file encoding / id3tag encoding?

Other question, does deefuzzer use "ID3tags" or only mp3 filename?

**Comment by yomguy** [comment]
Hi @ChoiZ, could you test again against the last dev branch?

**Comment by ChoiZ** [comment]
Ok I'll upgrade it.

**Comment by ChoiZ** [comment]
Seems works well.
