### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by kprkpr** [yomguy/DeeFuzzer#77]
I dont know why but I can not start deefuzzer.. throws this error:
Traceback (most recent call last):
  File "/usr/local/bin/deefuzzer", line 56, in <module>
    main()
  File "/usr/local/bin/deefuzzer", line 48, in main
    d = deefuzzer.core.DeeFuzzer(sys.argv[-1])
  File "/usr/local/lib/python2.7/dist-packages/deefuzzer/core.py", line 69, in __init__
    self.conf = get_conf_dict(self.conf_file)
  File "/usr/local/lib/python2.7/dist-packages/deefuzzer/tools/utils.py", line 93, in get_conf_dict
    return xmltodict(data, 'utf-8')
  File "/usr/local/lib/python2.7/dist-packages/deefuzzer/tools/xmltodict.py", line 38, in xmltodict
    return indexchilds(dom, enc)
  File "/usr/local/lib/python2.7/dist-packages/deefuzzer/tools/xmltodict.py", line 23, in indexchilds
    v = indexchilds(childnode, enc)
  File "/usr/local/lib/python2.7/dist-packages/deefuzzer/tools/xmltodict.py", line 23, in indexchilds
    v = indexchilds(childnode, enc)
  File "/usr/local/lib/python2.7/dist-packages/deefuzzer/tools/xmltodict.py", line 25, in indexchilds
    v = childnode.childNodes[0].nodeValue.encode(enc)
IndexError: tuple index out of range

My config file is:
http://pastebin.com/zEsH5nYQ

**Comment by yomguy** [comment]
Hi,
Sorry but you cannot use the documented XML example for now. Althrough we are going to change the XML parser which will fix that, you might start you config file with example/deefuzzer.xml or example/deefuzzer.json or example/deefuzzer.json.

**Comment by kprkpr** [comment]
great! Now works

Hmm.. But I dont know how to do to relay a live stream when it are, and when there arent, music files of the computer (Auto-conmuting)

**Comment by yomguy** [comment]
There is no such automatic switch but could be done with a little file system check indeed.
But I wonder how you could have some files or not in your usecase...
I'm closing this issue because your primary need is satisfied ;)
