### ISSUE TITLE
OSCController object has no attribute 

### ISSUE THREAD

**Issue by robnoordt** [yomguy/DeeFuzzer#99]
###  #Hi,

Starting Deefuzzer as daemon works without problems: deefuzzer /etc/DeeFuzzer/deefuzzer.yaml &
Ok, one stream but I like to have more streams. This should be possible in Deefuzzer. So editing the deefuzzer_multiple.yaml file for two stations.
>
deefuzzer: 
 log: "/var/log/deefuzzer/multi.log"
 m3u: "/tmp/station.m3u"
 stationdefaults: 
  control: 
   mode: 1
   port: 16001
  jingles: 
   dir: "/media/DRIVE2GO/jinglesRadioRenzo"
   mode: 1
   shuffle: 1
 station: 
 - 
   control: 
    mode: 1
    port: 16001
   infos: 
    description: "radioRenzo Offshore broadcasts"
    genre: "Various"
    name: "radioRenzo offshore radio broadcasts"
    short_name: RadioRenzo offshore radio broadcasts
    url: "https://radiorenzo.nl-web.net"
   jingles: 
    dir: "/media/DRIVE2GO/jinglesRadioRenzo"
    mode: 1
    shuffle: 1
   media: 
    bitrate: 96
    source: "/media/DRIVE2GO/RadioDiv/uitzendingen_programmas"
    format: mp3
    ogg_quality: 4
    samplerate: 48000
    shuffle: 1
    voices: 2
   record: 
    dir: "/path/to/archives"
    mode: 0
   relay: 
    author: Unknown
    mode: 0
    url: "http://127.0.0.1:8000/telecaster_live.mp3"
   feeds: 
    mode: 0
    rss: 1
    json: 0
    playlist: 1
    dir: "/path/to/rss/"
    enclosure: 1
    media_url: "http://localhost/media/"
   server: 
    host: "127.0.0.1"
    mountpoint: monitor0
    port: 8000
    public: 1
    sourcepassword: *****
    type: icecast
    appendtype: 1
   twitter: 
    key: "your access token key"
    mode: 0
    secret: "your access token secret key"
    tags: "parisson deefuzzer"
 - 
   control: 
    mode: 1
    port: 16001
   infos: 
    description: "radiorenzo musical History tour"
    genre: "Various top40 hits"
    name: "radiorenzo musical History tour"
    short_name: radiorenzo musical History tour
    url: "http://radiorenzo.nl-web.net"
   jingles: 
    dir: "/media/DRIVE2GO/jinglesRadiorenzo40"
    mode: 1
    shuffle: 1
   media: 
    bitrate: 96
    source: "/media/DRIVE2GO/muziek/top 40_1965-heden"
    format: mp3
    ogg_quality: 4
    samplerate: 48000
    shuffle: 1
    voices: 2
   record: 
    dir: "/path/to/archives"
    mode: 0
   relay: 
    author: Unknown
    mode: 0
    url: "http://127.0.0.1:8000/telecaster_live.mp3"
   feeds: 
    mode: 0
    rss: 1
    json: 0
    playlist: 1
    dir: "/path/to/rss/"
    enclosure: 1
    media_url: "http://localhost/media/"
   server: 
    host: "127.0.0.1"
    mountpoint: monitor1
    port: 8000
    public: 1
    sourcepassword: *****
    type: icecast
    appendtype: 1
   twitter: 
    key: "your access token key"
    mode: 0
    secret: "your access token secret key"
    tags: "parisson deefuzzer"
<
But this gives one error and stream “monitor1 ” does not work.
>
           deefuzzer /etc/DeeFuzzer/deefuzzer_MultiRenzo.yaml
root@raspberry3:~# deefuzzer /etc/DeeFuzzer/deefuzzer_MultiRenzo.yaml &
[4] 26383
root@raspberry3:~# server error 9904: b'cannot find free port'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/core.py", line 317, in run
    new_station = Station(self.station_settings[i], q, self.log_queue, self.m3u)
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/station.py", line 257, in __init__
    self.osc_controller.add_method('/media/next', 'i', self.media_next_callback)
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/tools/osc.py", line 39, in add_method
    self.server.add_method(path, type, method)
'OSCController' object has no attribute 'server'

<

Also, browsing to localIP:16001 does not work. No page is bean showed here.
Any suggestions what’s going wrong here?

**Comment by yomguy** [comment]
The OSCController is only an interface to controm DeeFuzzer by OSC messages.
In your configuration, 2 same ports are assigned for 2 different channels which is not allowed.
Please use 2 different OSC ports or disable the controller setting each `<control><mode>` to 0.

**Comment by robnoordt** [comment]
Hi,

Ok, changed to monitor 0 and monitor1. Thad works. Great! Two other issues;
When Also, browsing to localIP:16001 does not work. No page is bean showed here.
And, one other thing; when streaming this two (icecast)stations(in both cases it is shuffling a directory with mp3 files) It stops playing after one or two tracks.

Wat could be a reason and a solution for this two cases? Suggestions?

**Comment by robnoordt** [comment]
Ok, about what I reported above;
In the beginning I see that Win amp gives the error message when the streaming of MP3 files stops. Error synchronizing http: // streamsite. Is something going wrong with synchronization? And strange that this occurs when changing the played songs. It also happens connecting by internal network. That says, I think, nothing to do whit band wide.

**Comment by robnoordt** [comment]
Hi,

After midnight yet, coincidentally, I was experimenting. But Ok, I think I solved the problem that tracks stop playing. At least, that seems a bit like that now. Short time to actually test this, so we'll see that tomorrow.
What I've done; I created a m3u playlist of this folder with the valk media placer in the network of the directory to be played (which I indicated in the ml of Deefuzzer). Put this also in the root dir. of this dir. And now Deefuurzzer does play on. The jingles (I made this with a tts tool to convert text to speech) not entirely Ok. Another bitrate I think. I'll watch it tomorrow.

**Comment by robnoordt** [comment]
This is the last part of the logfile(/var/log/deefuzzer/deefuzzer.log)
2020-01-12 12:19:24,955 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:19:37,661 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:25:04,500 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:25:13,755 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:30:42,230 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:31:00,529 ERROR Station http://Raspberry3:8000/monitor1.mp3: could not send the buffer
2020-01-12 12:31:00,533 INFO Station http://Raspberry3:8000/monitor1.mp3: channel closed
2020-01-12 12:31:00,534 INFO Station http://Raspberry3:8000/monitor1.mp3: channel connected
2020-01-12 12:31:00,535 INFO Station http://Raspberry3:8000/monitor1.mp3: channel restarted
2020-01-12 12:31:11,022 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:31:22,558 ERROR Station http://Raspberry3:8000/monitor1.mp3: could not send the buffer
2020-01-12 12:31:22,559 INFO Station http://Raspberry3:8000/monitor1.mp3: channel closed
2020-01-12 12:31:22,567 INFO Station http://Raspberry3:8000/monitor1.mp3: channel connected
2020-01-12 12:31:22,571 INFO Station http://Raspberry3:8000/monitor1.mp3: channel restarted
2020-01-12 12:38:26,675 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:38:38,710 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:42:14,498 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)
2020-01-12 12:42:26,202 INFO Station http://Raspberry3:8000/monitor1.mp3: Generating new playlist (500 tracks)

**Comment by yomguy** [comment]
Hi @robnoordt, and sorry for th late reply. 
Please check your icecast configuration which by default is limited by 1 or 2 sources.
I will close this issue as the first subject is resolved. Please create a new one for the second if the pb persist after tuning the server.
